"""initial_schema

Revision ID: e56e139d2676
Revises: 
Create Date: 2026-04-11 04:15:57.892606

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e56e139d2676'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectures_id'), 'lectures', ['id'], unique=False)
    op.create_index(op.f('ix_lectures_title'), 'lectures', ['title'], unique=False)
    op.create_table('modules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='Display / learning order'),
    sa.Column('prerequisite_module_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='JSON array of Module UUIDs'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_modules_order_index', 'modules', ['order_index'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('available_hours_per_week', sa.Float(), nullable=True, comment='Self-reported hours available per week'),
    sa.Column('target_deadline', sa.Date(), nullable=True, comment='When the user wants to finish the curriculum'),
    sa.Column('preferred_method', sa.Enum('reading', 'video', name='preferred_method_enum'), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), server_default='false', nullable=False, comment='True once the user has completed the onboarding flow'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecture_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.create_table('qa_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecture_id', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('thoughts', sa.Text(), nullable=True),
    sa.Column('current_timestamp', sa.Float(), nullable=True),
    sa.Column('image_base64', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_history_id'), 'qa_history', ['id'], unique=False)
    op.create_table('topics',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('prerequisite_topic_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='JSON array of Topic UUIDs'),
    sa.Column('estimated_hours_beginner', sa.Float(), nullable=True),
    sa.Column('estimated_hours_intermediate', sa.Float(), nullable=True),
    sa.Column('estimated_hours_review', sa.Float(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True, comment='Learning material in Markdown format'),
    sa.Column('video_url', sa.String(length=500), nullable=True, comment='Primary video lecture URL'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topics_module_id', 'topics', ['module_id'], unique=False)
    op.create_index('ix_topics_module_order', 'topics', ['module_id', 'order_index'], unique=False)
    op.create_table('transcript_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecture_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_lines_id'), 'transcript_lines', ['id'], unique=False)
    op.create_index(op.f('ix_transcript_lines_start_time'), 'transcript_lines', ['start_time'], unique=False)
    op.create_table('knowledge_components',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kc_topic_id', 'knowledge_components', ['topic_id'], unique=False)
    op.create_table('learning_paths',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('skip', 'quick_review', 'standard_learn', 'deep_practice', 'remediate', name='path_action_enum'), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='Step order within the full path'),
    sa.Column('week_number', sa.Integer(), nullable=True, comment='Suggested calendar week (1-based)'),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'skipped', name='path_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lp_user_id', 'learning_paths', ['user_id'], unique=False)
    op.create_index('ix_lp_user_order', 'learning_paths', ['user_id', 'order_index'], unique=False)
    op.create_index('ix_lp_user_status', 'learning_paths', ['user_id', 'status'], unique=False)
    op.create_table('questions',
    sa.Column('item_id', sa.String(length=50), nullable=False, comment='Human-readable unique identifier, e.g. ITEM-001-00001'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'calibrated', 'retired', name='question_status_enum'), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('bloom_level', sa.Enum('remember', 'understand', 'apply', 'analyze', name='bloom_level_enum'), nullable=False),
    sa.Column('difficulty_bucket', sa.Enum('easy', 'medium', 'hard', name='difficulty_bucket_enum'), nullable=False),
    sa.Column('stem_text', sa.Text(), nullable=False),
    sa.Column('stem_media', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Optional media metadata (url, type, alt)'),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Enum('A', 'B', 'C', 'D', name='correct_answer_enum'), nullable=False),
    sa.Column('distractor_a_rationale', sa.Text(), nullable=True),
    sa.Column('distractor_b_rationale', sa.Text(), nullable=True),
    sa.Column('distractor_c_rationale', sa.Text(), nullable=True),
    sa.Column('distractor_d_rationale', sa.Text(), nullable=True),
    sa.Column('misconception_a_id', sa.String(length=100), nullable=True),
    sa.Column('misconception_b_id', sa.String(length=100), nullable=True),
    sa.Column('misconception_c_id', sa.String(length=100), nullable=True),
    sa.Column('misconception_d_id', sa.String(length=100), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('time_expected_seconds', sa.Integer(), nullable=True),
    sa.Column('usage_context', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='JSON array: assessment | quiz | module_test'),
    sa.Column('kc_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='JSON array of KnowledgeComponent UUIDs'),
    sa.Column('irt_difficulty', sa.Float(), nullable=True),
    sa.Column('irt_discrimination', sa.Float(), nullable=True),
    sa.Column('irt_guessing', sa.Float(), nullable=True),
    sa.Column('total_responses', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_bloom_difficulty', 'questions', ['bloom_level', 'difficulty_bucket'], unique=False)
    op.create_index(op.f('ix_questions_item_id'), 'questions', ['item_id'], unique=True)
    op.create_index('ix_questions_module_id', 'questions', ['module_id'], unique=False)
    op.create_index('ix_questions_status', 'questions', ['status'], unique=False)
    op.create_index('ix_questions_topic_id', 'questions', ['topic_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.Enum('assessment', 'quiz', 'module_test', 'practice', name='session_type_enum'), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('module_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('score_percent', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('score_percent >= 0 AND score_percent <= 100', name='ck_score_range'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_started_at', 'sessions', ['started_at'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_index('ix_sessions_user_type', 'sessions', ['user_id', 'session_type'], unique=False)
    op.create_table('interactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('sequence_position', sa.Integer(), nullable=False),
    sa.Column('global_sequence_position', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.Enum('A', 'B', 'C', 'D', name='selected_answer_enum'), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('changed_answer', sa.Boolean(), nullable=False),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('explanation_viewed', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interactions_global_seq', 'interactions', ['user_id', 'global_sequence_position'], unique=False)
    op.create_index('ix_interactions_question_id', 'interactions', ['question_id'], unique=False)
    op.create_index('ix_interactions_session_id', 'interactions', ['session_id'], unique=False)
    op.create_index('ix_interactions_user_id', 'interactions', ['user_id'], unique=False)
    op.create_index('ix_interactions_user_timestamp', 'interactions', ['user_id', 'timestamp'], unique=False)
    op.create_table('mastery_scores',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('kc_id', sa.UUID(), nullable=True, comment='NULL means score is at topic grain, not KC grain'),
    sa.Column('mastery_probability', sa.Float(), nullable=False),
    sa.Column('mastery_level', sa.Enum('not_started', 'novice', 'developing', 'proficient', 'mastered', name='mastery_level_enum'), nullable=False),
    sa.Column('bloom_max_achieved', sa.String(length=50), nullable=True, comment='Highest Bloom level demonstrated (remember → analyze)'),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('recent_trend', sa.Enum('improving', 'stable', 'declining', name='recent_trend_enum'), nullable=True),
    sa.Column('last_practiced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('mastery_probability >= 0 AND mastery_probability <= 1', name='ck_mastery_probability_range'),
    sa.ForeignKeyConstraint(['kc_id'], ['knowledge_components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', 'kc_id', name='uq_mastery_user_topic_kc')
    )
    op.create_index('ix_mastery_user_id', 'mastery_scores', ['user_id'], unique=False)
    op.create_index('ix_mastery_user_topic', 'mastery_scores', ['user_id', 'topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mastery_user_topic', table_name='mastery_scores')
    op.drop_index('ix_mastery_user_id', table_name='mastery_scores')
    op.drop_table('mastery_scores')
    op.drop_index('ix_interactions_user_timestamp', table_name='interactions')
    op.drop_index('ix_interactions_user_id', table_name='interactions')
    op.drop_index('ix_interactions_session_id', table_name='interactions')
    op.drop_index('ix_interactions_question_id', table_name='interactions')
    op.drop_index('ix_interactions_global_seq', table_name='interactions')
    op.drop_table('interactions')
    op.drop_index('ix_sessions_user_type', table_name='sessions')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_started_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_questions_topic_id', table_name='questions')
    op.drop_index('ix_questions_status', table_name='questions')
    op.drop_index('ix_questions_module_id', table_name='questions')
    op.drop_index(op.f('ix_questions_item_id'), table_name='questions')
    op.drop_index('ix_questions_bloom_difficulty', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_lp_user_status', table_name='learning_paths')
    op.drop_index('ix_lp_user_order', table_name='learning_paths')
    op.drop_index('ix_lp_user_id', table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index('ix_kc_topic_id', table_name='knowledge_components')
    op.drop_table('knowledge_components')
    op.drop_index(op.f('ix_transcript_lines_start_time'), table_name='transcript_lines')
    op.drop_index(op.f('ix_transcript_lines_id'), table_name='transcript_lines')
    op.drop_table('transcript_lines')
    op.drop_index('ix_topics_module_order', table_name='topics')
    op.drop_index('ix_topics_module_id', table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_qa_history_id'), table_name='qa_history')
    op.drop_table('qa_history')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_modules_order_index', table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_lectures_title'), table_name='lectures')
    op.drop_index(op.f('ix_lectures_id'), table_name='lectures')
    op.drop_table('lectures')
    # ### end Alembic commands ###
