apiVersion: 1

datasources:
  - name: Prometheus
    uid: PBFA97CFB590B2093
    type: prometheus
    access: proxy
    url: http://prometheus.obs.a20-prod.internal:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://loki.obs.a20-prod.internal:3100
    editable: true

  - name: Postgres
    uid: Postgres
    type: postgres
    access: proxy
    url: $POSTGRES_HOST:$POSTGRES_PORT
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: $POSTGRES_DB
      sslmode: require
      postgresVersion: 1600
    editable: true
